version: '3.9'

name: librarian

networks:
  app_database_network:
    driver: host
  app_network:
    driver: host

services:

  # App database
  app_db:
    container_name: librarian_db
    tty: true
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app_database_network
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - ../mysqldata:/var/lib/mysql
      - ./docker/mariadb/config/my.cnf:/etc/mysql/conf.d/my.cnf
 


  # Application
  app:
    container_name: librarian_app
    tty: true
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./docker/app/entrypoint.sh:/entrypoint.sh
      - ./docker/app/config/app.ini:/usr/local/etc/php/conf.d/app.ini
      - ./docker/app/config/supervisord.conf:/etc/supervisord.conf
      - ./:/var/www
    working_dir: /var/www
    networks:
      - app_network
      - app_database_network
    expose:
      - 9000
    ports:
      - 5173:5173
    depends_on:
      - app_db
    extra_hosts:
      - host.docker.internal:host-gateway
      - africanmusic.org:host-gateway
      - chem.vt.edu:host-gateway
      - wellspringafrica.org:host-gateway


  # Nginx webserver
  nginx:
    container_name: librarian_nginx
    tty: true
    image: nginx:stable-alpine
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/config/local.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - app
    networks:
      - app_network

  # PhpMyAdmin available on :8888 port
  phpmyadmin:
    container_name: librarian_phpmyadmin
    image: phpmyadmin:apache
    restart: always
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: app_db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 2G
      MEMORY_LIMIT: 2048M
      HIDE_PHP_VERSION: 1
    networks:
      - app_database_network
    ports:
      - 8888:80
    depends_on:
      - app_db

